name: Commit burst (25)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  burst:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Make 25 commits
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

          # файл, в который будем писать «пульс»
          touch pulse.md
          if ! git ls-files --error-unmatch pulse.md >/dev/null 2>&1; then
            echo "# pulse" > pulse.md
            git add pulse.md
            git commit -m "init pulse"
          fi

          for i in $(seq 1 25); do
            echo "$(date -u)  $i" >> pulse.md
            git add pulse.md
            git commit -m "pulse $i"
          done

          # пушим в текущую ветку (обычно main)
          git push
