name: Daily heartbeat
on:
  schedule:
    - cron: "7 0 * * *"    # один раз в день (UTC)
  workflow_dispatch:
permissions:
  contents: write
jobs:
  beat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          echo "$(date -u)" >> heartbeat.txt
          git add heartbeat.txt
          git commit -m "chore: daily heartbeat" || echo "nothing to commit"
          git push
